In [33]:

import numpy as np


arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

print(arr.reshape(5 , 3))

print(arr.reshape(3 , 5))



[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [3]:
print(arr[3])
print(arr[6])
print(arr[7])

4
7
8


In [7]:
print(arr[4 : 13])

[ 5  6  7  8  9 10 11 12 13]


In [31]:
from numpy import random as rand

rand.choice(arr ,4)

array([10, 12, 13, 15])