In [9]:
import numpy as np


a1 = np.array([1,2,3,4,5,6,7,8,9,0])
a2 = np.array([ 11 , 12 , 13 , 14 , 15 , 16 , 17 , 18 , 19 , 20])



a3 = np.hstack(np.vstack(np.append(a2 , a1)))
print(a3)


sort_asc = np.sort(a1)

print(sort_asc)

sort_dec = np.sort(a2)[::-1]
print(sort_dec)

[11 12 13 14 15 16 17 18 19 20  1  2  3  4  5  6  7  8  9  0]
[0 1 2 3 4 5 6 7 8 9]
[20 19 18 17 16 15 14 13 12 11]
